name: Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: integration-tests
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Integration tests
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: cargo test --test integration_test -- --ignored
